Add issues templates
cartesi/playground pull request #1
Opened 2023-05-25 16:01 UTC by diegonehab

Copied commit from the machine-emulator repo.

2023-05-25 16:43 UTC, mpolitzer approved these changes
LGTM

2023-05-25 16:44 UTC, mpolitzer requested changes

2023-05-25 16:44 UTC, mpolitzer commented on .github/pull_request_template.md
> +If you would like to contribute please read [CONTRIBUTING.md](https://github.com/cartesi/machine-emulator/blob/main/CONTRIBUTING.md).
Can this be repo agnostic?

2023-05-26 13:53 UTC, diegonehab commented on .github/pull_request_template.md
> +If you would like to contribute please read [CONTRIBUTING.md](https://github.com/cartesi/machine-emulator/blob/main/CONTRIBUTING.md).
Done. Made it relative.

2023-05-26 14:03 UTC, mpolitzer approved these changes, later dismissed

2023-06-06 19:38 UTC, edubart commented on .github/pull_request_template.md
> +If you would like to contribute please read [CONTRIBUTING.md](../../blob/main/CONTRIBUTING.md).
I think @vfusco wants this to be changed like he did in other repositories.

2023-06-09 14:23 UTC, edubart approved these changes

2023-06-12 22:42 UTC, vfusco approved these changes

2023-06-12 22:47 UTC, mpolitzer approved these changes

2023-07-06 16:24 UTC, merged